# Generated by Django 5.2.7 on 2026-01-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_usernotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FcmTokenModel',
        ),
    ]
