# Generated by Django 4.2.24 on 2025-12-09 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name in English', max_length=200)),
                ('name_sw', models.CharField(help_text='Template name in Swahili', max_length=200)),
                ('description', models.TextField(help_text='Template description in English')),
                ('description_sw', models.TextField(help_text='Template description in Swahili')),
                ('category', models.CharField(choices=[('employment', 'Employment Documents'), ('legal_notice', 'Legal Notices'), ('resignation', 'Resignation Documents'), ('questionnaire', 'Questionnaires'), ('general', 'General Documents')], max_length=50)),
                ('template_content_en', models.TextField(help_text='HTML template with {{placeholder}} syntax for English')),
                ('template_content_sw', models.TextField(help_text='HTML template with {{placeholder}} syntax for Swahili')),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in TZS (0 for free templates)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for template (e.g., 📄, 📝)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_documents/%Y/%m/')),
                ('document_title', models.CharField(blank=True, help_text='Custom title given by user', max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to='document_templates.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Document',
                'verbose_name_plural': 'User Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section name in English', max_length=200)),
                ('name_sw', models.CharField(help_text='Section name in Swahili', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Section description in English')),
                ('description_sw', models.TextField(blank=True, help_text='Section description in Swahili')),
                ('order', models.IntegerField(default=0, help_text='Display order within template')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='document_templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'Template Section',
                'verbose_name_plural': 'Template Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'employee_name', 'start_date')", max_length=100)),
                ('label_en', models.CharField(help_text='Field label in English', max_length=200)),
                ('label_sw', models.CharField(help_text='Field label in Swahili', max_length=200)),
                ('placeholder_en', models.CharField(blank=True, help_text='Placeholder text in English', max_length=200)),
                ('placeholder_sw', models.CharField(blank=True, help_text='Placeholder text in Swahili', max_length=200)),
                ('help_text_en', models.TextField(blank=True, help_text='Help text in English')),
                ('help_text_sw', models.TextField(blank=True, help_text='Help text in Swahili')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text / Paragraph'), ('email', 'Email Address'), ('phone', 'Phone Number'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('signature', 'Signature')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within section/template')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text="JSON: {min_length: 3, max_length: 100, pattern: '^[A-Z]', etc.}")),
                ('options', models.JSONField(blank=True, default=list, help_text="JSON array for dropdown/radio: ['Option 1', 'Option 2']")),
                ('options_sw', models.JSONField(blank=True, default=list, help_text='JSON array for Swahili options')),
                ('default_value', models.TextField(blank=True)),
                ('section', models.ForeignKey(blank=True, help_text='Optional: group field under a section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='document_templates.templatesection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='document_templates.documenttemplate')),
            ],
            options={
                'verbose_name': 'Template Field',
                'verbose_name_plural': 'Template Fields',
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='UserDocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text="User's input for this field")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='document_templates.templatefield')),
                ('user_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_data', to='document_templates.userdocument')),
            ],
            options={
                'verbose_name': 'User Document Data',
                'verbose_name_plural': 'User Document Data',
                'indexes': [models.Index(fields=['user_document', 'field'], name='document_te_user_do_518326_idx')],
                'unique_together': {('user_document', 'field')},
            },
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['user', '-created_at'], name='document_te_user_id_6a034f_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['template', 'status'], name='document_te_templat_7b0c26_idx'),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['status', '-created_at'], name='document_te_status_3b09cb_idx'),
        ),
        migrations.AddIndex(
            model_name='templatefield',
            index=models.Index(fields=['template', 'order'], name='document_te_templat_b92659_idx'),
        ),
        migrations.AddIndex(
            model_name='templatefield',
            index=models.Index(fields=['section', 'order'], name='document_te_section_d40c6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatefield',
            unique_together={('template', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['category', 'is_active'], name='document_te_categor_6a804b_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_active', 'order'], name='document_te_is_acti_4d1f03_idx'),
        ),
    ]
