# Generated by Django 5.2.7 on 2026-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title in English', max_length=255)),
                ('title_sw', models.CharField(blank=True, help_text='Document title in Swahili', max_length=255, null=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('terms', 'Terms of Service'), ('conditions', 'Conditions'), ('privacy', 'Privacy Policy'), ('faq', 'FAQ'), ('help', 'Help Documentation'), ('about', 'About Us'), ('general', 'General Content')], default='general', help_text='Document category', max_length=50)),
                ('content', models.TextField(help_text='Markdown content in English')),
                ('content_sw', models.TextField(blank=True, help_text='Markdown content in Swahili', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this document is active/visible')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this document is publicly accessible')),
                ('display_order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Content',
                'verbose_name_plural': 'Document Contents',
                'ordering': ['category', 'display_order', 'title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='document_te_categor_33a915_idx'), models.Index(fields=['slug'], name='document_te_slug_73d6a0_idx')],
            },
        ),
    ]
