# Generated by Django 5.2.7 on 2026-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatuteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (English)', max_length=255)),
                ('name_sw', models.CharField(help_text='Category name (Swahili)', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_sw', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statute Category',
                'verbose_name_plural': 'Statute Categories',
                'db_table': 'statute_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title (English)', max_length=500)),
                ('title_sw', models.CharField(help_text='Title (Swahili)', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('description_sw', models.TextField(blank=True, default='')),
                ('file', models.FileField(help_text='PDF file for this law', upload_to='statutes/pdfs/%Y/%m/')),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='File size in bytes')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='statutes', to='statutes.statutecategory')),
            ],
            options={
                'verbose_name': 'Statute',
                'verbose_name_plural': 'Statutes',
                'db_table': 'statutes',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
