# Generated by Django 5.2.7 on 2026-02-05 13:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Community Forum'), ('legal_ed', 'Legal Education')], db_index=True, default='students', help_text='Which hub this content belongs to', max_length=20)),
                ('content_type', models.CharField(choices=[('discussion', 'Discussion Post'), ('question', 'Question Post'), ('article', 'Article'), ('news', 'News'), ('announcement', 'Announcement'), ('document', 'General Document'), ('notes', 'Study Notes'), ('past_papers', 'Past Exam Papers'), ('assignments', 'Assignments'), ('research', 'Research Paper'), ('case_study', 'Case Study'), ('tutorial', 'Tutorial'), ('hub_content', 'Hub Content'), ('other', 'Other')], default='document', help_text='Type of content (post or document)', max_length=20)),
                ('uploader_type', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('advocate', 'Advocate'), ('admin', 'Admin')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Rich text content for posts (HTML/Markdown)')),
                ('is_lecture_material', models.BooleanField(default=False, help_text='Indicates if this is official lecture material (uploaded by lecturer)')),
                ('is_verified_quality', models.BooleanField(default=False, help_text='Lecturer-verified or platform-verified quality content')),
                ('file', models.FileField(blank=True, help_text='File content (PDF, DOC, etc) - Optional for text posts', null=True, upload_to='learning_materials/')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('video_url', models.URLField(blank=True, help_text='Embedded video link (YouTube, Vimeo, etc)', null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', help_text='Content language', max_length=2)),
                ('is_downloadable', models.BooleanField(default=True, help_text='Allow users to download this material')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price in TZS (0 = free)', max_digits=10)),
                ('downloads_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0, help_text='Number of times content was viewed (not downloaded)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('uploader_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Platform's share of revenue", max_digits=12)),
                ('is_approved', models.BooleanField(default=True, help_text='Admin approval (auto-approve posts, review documents)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub Content',
                'verbose_name_plural': 'Hub Contents',
                'db_table': 'subscriptions_learningmaterial',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterialPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Learning Material Purchase',
                'verbose_name_plural': 'Learning Material Purchases',
                'db_table': 'subscriptions_learningmaterialpurchase',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='LecturerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Notify student when lecturer uploads new material')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecturer Follow',
                'verbose_name_plural': 'Lecturer Follows',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_answered_by_uploader', models.BooleanField(default=False, help_text='True if answered by the material uploader (lecturer)')),
                ('helpful_count', models.IntegerField(default=0, help_text='How many found this Q&A helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Question',
                'verbose_name_plural': 'Material Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1)])),
                ('review', models.TextField(blank=True, help_text='Optional written review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Rating',
                'verbose_name_plural': 'Material Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
