# Generated by Django 5.2.7 on 2025-10-22 15:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('hubs', '0008_rename_to_hub_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Hub Content', 'verbose_name_plural': 'Hub Contents'},
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='learningmaterial',
            name='rich_text_content',
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content for posts (HTML/Markdown)'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='hub_type',
            field=models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Community Forum'), ('legal_ed', 'Legal Education')], db_index=True, default='students', help_text='Which hub this content belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin to top of feed'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='platform_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Platform's share of revenue", max_digits=12),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='video_url',
            field=models.URLField(blank=True, help_text='Embedded video link (YouTube, Vimeo, etc)', null=True),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='content_type',
            field=models.CharField(choices=[('discussion', 'Discussion Post'), ('question', 'Question Post'), ('article', 'Article'), ('news', 'News'), ('announcement', 'Announcement'), ('document', 'General Document'), ('notes', 'Study Notes'), ('past_papers', 'Past Exam Papers'), ('assignments', 'Assignments'), ('research', 'Research Paper'), ('case_study', 'Case Study'), ('tutorial', 'Tutorial'), ('hub_content', 'Hub Content'), ('other', 'Other')], default='document', help_text='Type of content (post or document)', max_length=20),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='File content (PDF, DOC, etc) - Optional for text posts', null=True, upload_to='learning_materials/'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin approval (auto-approve posts, review documents)'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price in TZS (0 = free)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Link to Legal Ed subtopic (for legal_ed hub only)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledsubtopic'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='uploader_type',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('advocate', 'Advocate'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['hub_type', 'content_type', '-created_at'], name='subscriptio_hub_typ_91434c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['uploader', '-created_at'], name='subscriptio_uploade_dbe7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['price'], name='subscriptio_price_5a24a1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['is_approved', 'is_active'], name='subscriptio_is_appr_b0288c_idx'),
        ),
    ]
