# Generated by Django 5.2.7 on 2026-02-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('hubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Link to Legal Ed subtopic (for legal_ed hub only) - DEPRECATED: Use topic instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledsubtopic'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Direct link to Legal Ed topic (NEW: recommended over subtopic)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledtopic'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningmaterialpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningmaterialpurchase',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='documents.learningmaterial'),
        ),
        migrations.AddField(
            model_name='lecturerfollow',
            name='lecturer',
            field=models.ForeignKey(help_text='Lecturer being followed', on_delete=django.db.models.deletion.CASCADE, related_name='student_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturerfollow',
            name='student',
            field=models.ForeignKey(help_text='Student following the lecturer', on_delete=django.db.models.deletion.CASCADE, related_name='following_lecturers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialquestion',
            name='answered_by',
            field=models.ForeignKey(blank=True, help_text='Person who answered (lecturer preferred)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_questions_answered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialquestion',
            name='asker',
            field=models.ForeignKey(help_text='Student asking the question', on_delete=django.db.models.deletion.CASCADE, related_name='material_questions_asked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialquestion',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Optional: The material this question is about (if material-specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.learningmaterial'),
        ),
        migrations.AddField(
            model_name='materialrating',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='documents.learningmaterial'),
        ),
        migrations.AddField(
            model_name='materialrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['hub_type', 'content_type', '-created_at'], name='subscriptio_hub_typ_91434c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['uploader', '-created_at'], name='subscriptio_uploade_dbe7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['price'], name='subscriptio_price_5a24a1_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['is_approved', 'is_active'], name='subscriptio_is_appr_b0288c_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['topic', '-created_at'], name='subscriptio_topic_i_3dd6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['subtopic', '-created_at'], name='subscriptio_subtopi_a06155_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningmaterialpurchase',
            unique_together={('buyer', 'material')},
        ),
        migrations.AddIndex(
            model_name='lecturerfollow',
            index=models.Index(fields=['student', '-followed_at'], name='documents_l_student_99d520_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturerfollow',
            index=models.Index(fields=['lecturer', '-followed_at'], name='documents_l_lecture_bd1fd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturerfollow',
            unique_together={('student', 'lecturer')},
        ),
        migrations.AddIndex(
            model_name='materialquestion',
            index=models.Index(fields=['material', 'status', '-created_at'], name='documents_m_materia_a9abe5_idx'),
        ),
        migrations.AddIndex(
            model_name='materialquestion',
            index=models.Index(fields=['asker', '-created_at'], name='documents_m_asker_i_26899d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialquestion',
            index=models.Index(fields=['answered_by', '-answered_at'], name='documents_m_answere_eb742d_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrating',
            index=models.Index(fields=['material', '-created_at'], name='documents_m_materia_803736_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrating',
            index=models.Index(fields=['rating'], name='documents_m_rating_859bcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialrating',
            unique_together={('material', 'rater')},
        ),
    ]
