# Generated by Django 5.2.7 on 2026-06-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('hubs', '0012_alter_legaledsubtopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Link to Legal Ed subtopic (Primary categorization for legal_ed hub)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledsubtopic'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Direct link to Legal Ed topic (Optional: auto-derived from subtopic)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledtopic'),
        ),
    ]
