# Generated by Django 5.2.7 on 2025-10-28 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_student_lecturer_interaction'),
        ('hubs', '0010_remove_advocatecommentlike_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Direct link to Legal Ed topic (NEW: recommended over subtopic)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledtopic'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Link to Legal Ed subtopic (for legal_ed hub only) - DEPRECATED: Use topic instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledsubtopic'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['topic', '-created_at'], name='subscriptio_topic_i_3dd6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaterial',
            index=models.Index(fields=['subtopic', '-created_at'], name='subscriptio_subtopi_a06155_idx'),
        ),
    ]
