# Generated by Django 5.2.7 on 2025-12-01 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_topic_to_learning_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialquestion',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Optional: The material this question is about (if material-specific)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.learningmaterial'),
        ),
    ]
