"""
Call Management Views for Incoming Calls via FCM
Handles call initiation, acceptance, rejection, ending, and status tracking
"""

from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from django.db import transaction
from django.utils import timezone
from django.shortcuts import get_object_or_404
import logging

from .models import CallSession, UserCallCredit
from authentication.models import PolaUser
from authentication.device_models import UserDevice
from notification.models import UserOnlineStatus
from notification.google_firebase_service.push_notification.auth_api import GoogleAuth
from notification.google_firebase_service.push_notification.fcm_api import FCM

logger = logging.getLogger(__name__)


class CallManagementViewSet(viewsets.ViewSet):
    """
    ViewSet for managing incoming calls with FCM notifications
    
    Endpoints:
    - POST /calls/initiate/ - Initiate a call to a consultant
    - POST /calls/{id}/accept/ - Accept an incoming call
    - POST /calls/{id}/reject/ - Reject an incoming call
    - POST /calls/{id}/end/ - End an active call
    - POST /calls/{id}/missed/ - Mark call as missed
    - GET /calls/consultants/{consultant_id}/status/ - Check consultant online status
    """
    permission_classes = [IsAuthenticated]
    
    @action(detail=False, methods=['post'], url_path='initiate')
    def initiate(self, request):
        """
        Initiate a call to a consultant
        
        POST /api/v1/subscriptions/calls/initiate/
        {
            "consultant_id": 456,
            "channel_name": "call_456_1702567890123",  # Generated by frontend
            "call_type": "voice"  # or "video"
        }
        """
        logger.info("🔥 INITIATE METHOD CALLED IN CallManagementViewSet")
        user = request.user
        consultant_id = request.data.get('consultant_id')
        channel_name = request.data.get('channel_name')
        call_type = request.data.get('call_type', 'voice')
        
        # DEBUG: Log all received data
        logger.info(f"📥 Request from: {user.email} (User ID: {user.id})")
        logger.info(f"📥 consultant_id received: {consultant_id} (type: {type(consultant_id).__name__})")
        logger.info(f"📥 channel_name: {channel_name}")
        logger.info(f"📥 call_type: {call_type}")
        
        # Validation
        if not consultant_id:
            return Response({
                'error': 'consultant_id is required'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        if not channel_name:
            return Response({
                'error': 'channel_name is required',
                'hint': 'Generate channel_name in app using AgoraConfig.generateChannelName(consultantId)'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Get consultant (consultant_id is the ConsultantProfile ID)
        try:
            from .models import ConsultantProfile
            logger.info(f"🔍 Looking for ConsultantProfile with ID: {consultant_id}")
            consultant_profile = ConsultantProfile.objects.get(id=consultant_id)
            consultant = consultant_profile.user
            logger.info(f"✅ Found consultant: {consultant.email} (User ID: {consultant.id})")
        except ConsultantProfile.DoesNotExist:
            logger.error(f"❌ ConsultantProfile with ID {consultant_id} NOT FOUND")
            return Response({
                'error': 'consultant_not_found',
                'message': f'Consultant with ID {consultant_id} not found'
            }, status=status.HTTP_404_NOT_FOUND)
        
        # Check if user has credits
        active_credit = UserCallCredit.objects.filter(
            user=user,
            status='active',
            expiry_date__gt=timezone.now()
        ).order_by('-purchase_date').first()
        
        if not active_credit or active_credit.remaining_minutes <= 0:
            return Response({
                'error': 'insufficient_credits',
                'message': 'You don\'t have enough credits. Please purchase a bundle.',
                'credits_available': 0
            }, status=status.HTTP_402_PAYMENT_REQUIRED)
        
        # TODO: Re-enable online status check after testing
        # Check consultant online status (BYPASSED FOR TESTING)
        logger.info("⚠️ BYPASSING online status check for testing")
        # try:
        #     consultant_status = UserOnlineStatus.objects.get(user=consultant)
        #     if not consultant_status.is_available_for_call():
        #         status_message = {
        #             'offline': 'Consultant is currently offline',
        #             'busy': 'Consultant is currently on another call'
        #         }.get(consultant_status.status, 'Consultant is unavailable')
        #         
        #         return Response({
        #             'error': 'consultant_unavailable',
        #             'message': status_message,
        #             'consultant_status': consultant_status.status
        #         }, status=status.HTTP_503_SERVICE_UNAVAILABLE)
        # except UserOnlineStatus.DoesNotExist:
        #     # Auto-create online status for consultants without one (for development/testing)
        #     logger.warning(f"⚠️ Consultant {consultant.email} has no UserOnlineStatus. Creating one as 'available'.")
        #     try:
        #         consultant_status = UserOnlineStatus.objects.create(
        #             user=consultant,
        #             is_online=True,
        #             status='available',
        #             last_heartbeat=timezone.now()
        #         )
        #     except Exception as e:
        #         # If creating UserOnlineStatus fails (e.g., location API timeout), log and continue
        #         logger.error(f"❌ Failed to create UserOnlineStatus: {str(e)}")
        #         # Continue without status check for this call
        #         pass
        #     # Continue with the call initiation
        
        # Create call session
        with transaction.atomic():
            call_session = CallSession.objects.create(
                caller=user,
                consultant=consultant,
                channel_name=channel_name,
                call_type=call_type,
                status='ringing',
                call_credit=active_credit,
                initiated_at=timezone.now()
            )
            
            logger.info(f"📞 Call initiated: {user.email} → {consultant.email} (Call ID: {call_session.id})")
            logger.info(f"📺 Channel: {channel_name}")
        
        # DEBUG: Log consultant info
        logger.info(f"🔍 Looking for devices for consultant: {consultant.email} (User ID: {consultant.id})")
        
        # DEBUG: Check ALL devices for this consultant
        all_devices = UserDevice.objects.filter(user=consultant)
        logger.info(f"🔍 Total devices for consultant: {all_devices.count()}")
        for d in all_devices:
            logger.info(f"   Device {d.id}: {d.device_name} | active={d.is_active} | current={d.is_current_device} | fcm_token={bool(d.fcm_token)}")
        
        # Get consultant's devices with FCM token
        # First try current device, then fall back to any active device
        consultant_devices = UserDevice.objects.filter(
            user=consultant,
            is_current_device=True,
            is_active=True,
            fcm_token__isnull=False
        ).exclude(fcm_token='')
        
        logger.info(f"🔍 Devices with current=True, active=True, fcm_token: {consultant_devices.count()}")
        
        # If no current device, try any active device with FCM token
        if not consultant_devices.exists():
            consultant_devices = UserDevice.objects.filter(
                user=consultant,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='').order_by('-last_seen')
            logger.info(f"🔍 Fallback - Devices with active=True, fcm_token: {consultant_devices.count()}")
        
        if not consultant_devices.exists():
            call_session.status = 'cancelled'
            call_session.save()
            logger.warning(f"⚠️ Consultant {consultant.email} has no devices with FCM tokens")
            return Response({
                'error': 'consultant_no_devices',
                'message': 'Consultant has no registered devices for push notifications'
            }, status=status.HTTP_503_SERVICE_UNAVAILABLE)
        
        # Send FCM notifications to all consultant devices
        successful_notifications = 0
        
        for device in consultant_devices:
            try:
                # Get FCM access token (auto-reads project_id from service account file)
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                
                # Send notification
                fcm = FCM(project_id, access_token)
                call_data = {
                    'call_id': call_session.id,
                    'channel_name': channel_name,
                    'caller_id': user.id,
                    'caller_name': user.get_full_name() or user.email,
                    'caller_photo': user.profile_picture.url if hasattr(user, 'profile_picture') and user.profile_picture else '',
                    'call_type': call_type,
                    'timestamp': int(timezone.now().timestamp() * 1000)
                }
                
                status_code, response = fcm.send_call_notification(device.fcm_token, call_data)
                
                if status_code == 200:
                    successful_notifications += 1
                    logger.info(f"✅ FCM sent to device: {device.device_name or device.device_id[:8]}")
                else:
                    logger.error(f"❌ FCM failed for device {device.id}: {response}")
            
            except Exception as e:
                logger.error(f"❌ Error sending FCM to device {device.id}: {str(e)}")
                continue
        
        if successful_notifications == 0:
            return Response({
                'error': 'notification_failed',
                'message': 'Failed to send push notification to consultant'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        
        return Response({
            'success': True,
            'call_id': call_session.id,
            'channel_name': channel_name,
            'message': f'Call initiated. Notifying consultant ({successful_notifications} device(s))...',
            'consultant': {
                'id': consultant.id,
                'name': consultant.get_full_name() or consultant.email,
                'email': consultant.email
            }
        }, status=status.HTTP_201_CREATED)
    
    @action(detail=True, methods=['post'], url_path='accept')
    def accept(self, request, pk=None):
        """
        Accept an incoming call
        
        POST /api/v1/subscriptions/calls/{call_id}/accept/
        """
        call_session = get_object_or_404(CallSession, pk=pk)
        
        # Verify request user is the consultant
        if call_session.consultant != request.user:
            return Response({
                'error': 'unauthorized',
                'message': 'Only the consultant can accept this call'
            }, status=status.HTTP_403_FORBIDDEN)
        
        # Check if call is still ringing
        if call_session.status != 'ringing':
            return Response({
                'error': 'invalid_status',
                'message': f'Call cannot be accepted. Current status: {call_session.status}'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Accept the call
        with transaction.atomic():
            call_session.accept_call()
            
            # Mark consultant as busy
            consultant_status, created = UserOnlineStatus.objects.get_or_create(
                user=request.user
            )
            consultant_status.mark_busy()
            
            logger.info(f"✅ Call accepted: {call_session.caller.email} ← {request.user.email}")
        
        # Send notification to caller (call accepted)
        try:
            caller_devices = UserDevice.objects.filter(
                user=call_session.caller,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='')
            
            if caller_devices.exists():
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                fcm = FCM(project_id, access_token)
                
                status_data = {
                    'type': 'call_accepted',
                    'call_id': call_session.id,
                    'message': 'Call accepted. Join the channel.'
                }
                
                for device in caller_devices:
                    try:
                        fcm.send_call_status_notification(device.fcm_token, status_data)
                    except Exception as e:
                        logger.error(f"Error sending acceptance notification: {e}")
        
        except Exception as e:
            logger.error(f"Error notifying caller of acceptance: {e}")
        
        return Response({
            'success': True,
            'call_id': call_session.id,
            'channel_name': call_session.channel_name,
            'message': 'Call accepted. Joining channel...',
            'caller': {
                'id': call_session.caller.id,
                'name': call_session.caller.get_full_name() or call_session.caller.email,
                'photo': call_session.caller.profile_picture.url if hasattr(call_session.caller, 'profile_picture') and call_session.caller.profile_picture else ''
            }
        }, status=status.HTTP_200_OK)
    
    @action(detail=True, methods=['post'], url_path='reject')
    def reject(self, request, pk=None):
        """
        Reject an incoming call
        
        POST /api/v1/subscriptions/calls/{call_id}/reject/
        {
            "reason": "busy"  // optional
        }
        """
        call_session = get_object_or_404(CallSession, pk=pk)
        
        # Verify request user is the consultant
        if call_session.consultant != request.user:
            return Response({
                'error': 'unauthorized',
                'message': 'Only the consultant can reject this call'
            }, status=status.HTTP_403_FORBIDDEN)
        
        # Check if call is already rejected (idempotent behavior)
        if call_session.status == 'rejected':
            logger.info(f"Call {call_session.id} already rejected, returning success")
            return Response({
                'success': True,
                'message': 'Call already rejected',
                'already_rejected': True
            }, status=status.HTTP_200_OK)
        
        # Check if call is still ringing
        if call_session.status != 'ringing':
            return Response({
                'error': 'invalid_status',
                'message': f'Call cannot be rejected. Current status: {call_session.status}'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Reject the call
        reason = request.data.get('reason', 'rejected')
        call_session.reject_call()
        
        logger.info(f"❌ Call rejected: {call_session.caller.email} ← {request.user.email} (Reason: {reason})")
        
        # Send notification to caller (call rejected)
        try:
            caller_devices = UserDevice.objects.filter(
                user=call_session.caller,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='')
            
            if caller_devices.exists():
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                fcm = FCM(project_id, access_token)
                
                status_data = {
                    'type': 'call_rejected',
                    'call_id': call_session.id,
                    'message': f'Call {reason}'
                }
                
                for device in caller_devices:
                    try:
                        fcm.send_call_status_notification(device.fcm_token, status_data)
                    except Exception as e:
                        logger.error(f"Error sending rejection notification: {e}")
        
        except Exception as e:
            logger.error(f"Error notifying caller of rejection: {e}")
        
        return Response({
            'success': True,
            'message': 'Call rejected'
        }, status=status.HTTP_200_OK)
    
    @action(detail=True, methods=['post'], url_path='end')
    def end(self, request, pk=None):
        """
        End an active call
        
        POST /api/v1/subscriptions/calls/{call_id}/end/
        {
            "duration_seconds": 120  // optional, will calculate if not provided
        }
        """
        call_session = get_object_or_404(CallSession, pk=pk)
        
        # Verify request user is either caller or consultant
        if call_session.caller != request.user and call_session.consultant != request.user:
            return Response({
                'error': 'unauthorized',
                'message': 'Only call participants can end this call'
            }, status=status.HTTP_403_FORBIDDEN)
        
        # Check if call is active
        if call_session.status not in ['active', 'ringing']:
            return Response({
                'error': 'invalid_status',
                'message': f'Call cannot be ended. Current status: {call_session.status}'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # End the call
        duration_seconds = request.data.get('duration_seconds')
        ended_by = 'user' if call_session.caller == request.user else 'consultant'
        
        with transaction.atomic():
            call_session.end_call(ended_by=ended_by, duration_seconds=duration_seconds)
            
            # Mark consultant as available again
            try:
                consultant_status = UserOnlineStatus.objects.get(user=call_session.consultant)
                if consultant_status.status == 'busy':
                    consultant_status.mark_online()  # Back to available
            except UserOnlineStatus.DoesNotExist:
                pass
            
            logger.info(f"🔴 Call ended: {call_session.caller.email} ↔ {call_session.consultant.email}")
            logger.info(f"⏱️  Duration: {call_session.duration_minutes} minutes")
            logger.info(f"💰 Credits deducted: {call_session.credits_deducted}")
        
        # Get updated credit balance
        remaining_minutes = 0
        if call_session.call_credit:
            call_session.call_credit.refresh_from_db()
            remaining_minutes = call_session.call_credit.remaining_minutes
        
        # Send notification to the other participant (call ended)
        other_user = call_session.consultant if call_session.caller == request.user else call_session.caller
        try:
            other_devices = UserDevice.objects.filter(
                user=other_user,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='')
            
            if other_devices.exists():
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                fcm = FCM(project_id, access_token)
                
                status_data = {
                    'type': 'call_ended',
                    'call_id': call_session.id,
                    'message': f'Call ended by {request.user.get_full_name() or request.user.email}',
                    'duration_seconds': call_session.get_duration_seconds(),
                    'duration_minutes': call_session.duration_minutes
                }
                
                for device in other_devices:
                    try:
                        fcm.send_call_status_notification(device.fcm_token, status_data)
                        logger.info(f"📲 Call end notification sent to {other_user.email}")
                    except Exception as e:
                        logger.error(f"Error sending call end notification: {e}")
        
        except Exception as e:
            logger.error(f"Error notifying other participant of call end: {e}")
        
        return Response({
            'success': True,
            'call_summary': {
                'call_id': call_session.id,
                'duration_seconds': call_session.get_duration_seconds(),
                'duration_minutes': call_session.duration_minutes,
                'credits_deducted': float(call_session.credits_deducted),
                'credits_remaining': remaining_minutes
            },
            'message': 'Call ended successfully'
        }, status=status.HTTP_200_OK)
    
    @action(detail=True, methods=['post'], url_path='missed')
    def mark_missed(self, request, pk=None):
        """
        Mark call as missed (called by frontend after timeout)
        
        POST /api/v1/subscriptions/calls/{call_id}/missed/
        """
        call_session = get_object_or_404(CallSession, pk=pk)
        
        # Can be called by either caller or system
        if call_session.caller != request.user and not request.user.is_staff:
            return Response({
                'error': 'unauthorized',
                'message': 'Only the caller or admin can mark call as missed'
            }, status=status.HTTP_403_FORBIDDEN)
        
        # Check if call is still ringing
        if call_session.status != 'ringing':
            return Response({
                'error': 'invalid_status',
                'message': f'Call cannot be marked as missed. Current status: {call_session.status}'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Mark as missed
        call_session.mark_as_missed()
        
        logger.info(f"📵 Call missed: {call_session.caller.email} → {call_session.consultant.email}")
        
        # Send missed call notification to consultant
        try:
            consultant_devices = UserDevice.objects.filter(
                user=call_session.consultant,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='')
            
            if consultant_devices.exists():
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                fcm = FCM(project_id, access_token)
                
                status_data = {
                    'type': 'missed_call',
                    'call_id': call_session.id,
                    'message': f'You missed a call from {call_session.caller.get_full_name() or call_session.caller.email}'
                }
                
                for device in consultant_devices:
                    try:
                        fcm.send_call_status_notification(device.fcm_token, status_data)
                    except Exception as e:
                        logger.error(f"Error sending missed call notification: {e}")
        
        except Exception as e:
            logger.error(f"Error notifying consultant of missed call: {e}")
        
        return Response({
            'success': True,
            'message': 'Call marked as missed'
        }, status=status.HTTP_200_OK)
    
    @action(detail=True, methods=['post'], url_path='cancel')
    def cancel(self, request, pk=None):
        """
        Cancel a call (caller cancels before consultant answers)
        
        POST /api/v1/subscriptions/calls/{call_id}/cancel/
        """
        call_session = get_object_or_404(CallSession, pk=pk)
        
        # Only the caller can cancel
        if call_session.caller != request.user:
            return Response({
                'error': 'unauthorized',
                'message': 'Only the caller can cancel the call'
            }, status=status.HTTP_403_FORBIDDEN)
        
        # Check if call is still ringing
        if call_session.status != 'ringing':
            return Response({
                'error': 'invalid_status',
                'message': f'Call cannot be cancelled. Current status: {call_session.status}'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Mark as cancelled
        call_session.status = 'cancelled'
        call_session.save()
        
        logger.info(f"📵 Call cancelled: {call_session.caller.email} → {call_session.consultant.email}")
        
        # Send cancellation notification to consultant
        try:
            consultant_devices = UserDevice.objects.filter(
                user=call_session.consultant,
                is_active=True,
                fcm_token__isnull=False
            ).exclude(fcm_token='')
            
            if consultant_devices.exists():
                google_auth = GoogleAuth()
                access_token = google_auth.get_access_token()
                project_id = google_auth.get_project_id()
                fcm = FCM(project_id, access_token)
                
                status_data = {
                    'type': 'call_cancelled',
                    'call_id': call_session.id,
                    'message': f'{call_session.caller.get_full_name() or call_session.caller.email} cancelled the call'
                }
                
                for device in consultant_devices:
                    try:
                        fcm.send_call_status_notification(device.fcm_token, status_data)
                    except Exception as e:
                        logger.error(f"Error sending call cancelled notification: {e}")
        
        except Exception as e:
            logger.error(f"Error notifying consultant of cancelled call: {e}")
        
        return Response({
            'success': True,
            'message': 'Call cancelled successfully'
        }, status=status.HTTP_200_OK)
    
    @action(detail=False, methods=['get'], url_path='consultants/(?P<consultant_id>[^/.]+)/status')
    def consultant_status(self, request, consultant_id=None):
        """
        Check consultant online status and availability
        
        GET /api/v1/subscriptions/calls/consultants/{consultant_id}/status/
        """
        try:
            consultant = PolaUser.objects.get(id=consultant_id)
        except PolaUser.DoesNotExist:
            return Response({
                'error': 'consultant_not_found',
                'message': f'Consultant with ID {consultant_id} not found'
            }, status=status.HTTP_404_NOT_FOUND)
        
        try:
            online_status = UserOnlineStatus.objects.get(user=consultant)
            is_available = online_status.is_available_for_call()
            
            return Response({
                'consultant_id': consultant.id,
                'is_online': online_status.is_online,
                'is_available': is_available,
                'status': online_status.status,
                'last_seen': online_status.last_heartbeat.isoformat() if online_status.last_heartbeat else None
            }, status=status.HTTP_200_OK)
        
        except UserOnlineStatus.DoesNotExist:
            return Response({
                'consultant_id': consultant.id,
                'is_online': False,
                'is_available': False,
                'status': 'offline',
                'last_seen': None
            }, status=status.HTTP_200_OK)
    
    @action(detail=False, methods=['post'], url_path='check-credits')
    def check_credits(self, request):
        """
        Check if user has enough credits to call a consultant
        
        POST /api/v1/subscriptions/calls/check-credits/
        {
            "consultant_id": 123
        }
        """
        from .models import ConsultantProfile, CallCreditBundle
        
        consultant_id = request.data.get('consultant_id')
        
        if not consultant_id:
            return Response({
                'error': 'consultant_id is required'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Get consultant
        try:
            consultant = ConsultantProfile.objects.select_related('user').get(id=consultant_id)
        except ConsultantProfile.DoesNotExist:
            return Response({
                'error': 'Consultant not found'
            }, status=status.HTTP_404_NOT_FOUND)
        
        # Check consultant availability
        if not consultant.is_available:
            return Response({
                'has_credits': False,
                'error': 'Consultant is not available',
                'consultant': {
                    'id': consultant.id,
                    'name': consultant.user.get_full_name(),
                    'is_available': False
                }
            }, status=status.HTTP_400_BAD_REQUEST)
        
        # Get user's active credits
        active_credits = UserCallCredit.objects.filter(
            user=request.user,
            status='active',
            expiry_date__gt=timezone.now(),
            remaining_minutes__gt=0
        ).order_by('expiry_date')
        
        total_minutes = sum(credit.remaining_minutes for credit in active_credits)
        
        if total_minutes <= 0:
            # Get available bundles
            available_bundles = CallCreditBundle.objects.filter(is_active=True).order_by('price')
            
            bundles_data = [
                {
                    'id': bundle.id,
                    'name': bundle.name,
                    'name_sw': bundle.name_sw,
                    'minutes': bundle.minutes,
                    'price': float(bundle.price),
                    'price_formatted': f"TSh {float(bundle.price):,.0f}",
                    'validity_days': bundle.validity_days,
                    'description': bundle.description,
                }
                for bundle in available_bundles
            ]
            
            return Response({
                'has_credits': False,
                'available_minutes': 0,
                'consultant': {
                    'id': consultant.id,
                    'name': consultant.user.get_full_name(),
                    'consultant_type': consultant.consultant_type,
                    'specialization': consultant.specialization,
                    'rating': float(consultant.average_rating),
                },
                'message': 'You have no available call credits. Please purchase a bundle to continue.',
                'available_bundles': bundles_data,
                'purchase_url': '/api/v1/subscriptions/call-credits/purchase/'
            }, status=status.HTTP_402_PAYMENT_REQUIRED)
        
        return Response({
            'has_credits': True,
            'available_minutes': total_minutes,
            'active_credits_count': active_credits.count(),
            'consultant': {
                'id': consultant.id,
                'name': consultant.user.get_full_name(),
                'consultant_type': consultant.consultant_type,
                'specialization': consultant.specialization,
                'rating': float(consultant.average_rating),
                'years_of_experience': consultant.years_of_experience,
            },
            'credits_breakdown': [
                {
                    'id': credit.id,
                    'remaining_minutes': credit.remaining_minutes,
                    'expires_at': credit.expiry_date,
                    'bundle_name': credit.bundle.name if credit.bundle else 'Unknown'
                }
                for credit in active_credits
            ],
            'message': f'You have {total_minutes} minutes available. You can start the call.'
        }, status=status.HTTP_200_OK)
    
    @action(detail=False, methods=['get'], url_path='my-calls')
    def my_calls(self, request):
        """
        Get all incoming calls for the authenticated consultant
        Shows all call statuses: ringing, active, completed, rejected, missed, cancelled
        
        GET /api/v1/subscriptions/calls/my-calls/
        Query params:
        - page: Page number (default 1)
        - page_size: Results per page (default 20, max 100)
        - status: Filter by status (ringing, active, completed, rejected, missed, cancelled)
        """
        # Get all calls where user is the consultant
        calls = CallSession.objects.filter(
            consultant=request.user
        ).select_related('caller', 'consultant', 'call_credit__bundle').order_by('-initiated_at')
        
        # Apply status filter
        status_filter = request.query_params.get('status')
        if status_filter:
            calls = calls.filter(status=status_filter)
        
        # Pagination
        page = int(request.query_params.get('page', 1))
        page_size = min(int(request.query_params.get('page_size', 20)), 100)
        
        start = (page - 1) * page_size
        end = start + page_size
        
        total_count = calls.count()
        calls_page = calls[start:end]
        
        # Count by status
        status_counts = {
            'ringing': calls.filter(status='ringing').count(),
            'active': calls.filter(status='active').count(),
            'completed': calls.filter(status='completed').count(),
            'rejected': calls.filter(status='rejected').count(),
            'missed': calls.filter(status='missed').count(),
            'cancelled': calls.filter(status='cancelled').count(),
        }
        
        return Response({
            'count': total_count,
            'page': page,
            'page_size': page_size,
            'total_pages': (total_count + page_size - 1) // page_size,
            'status_counts': status_counts,
            'calls': [
                {
                    'id': call.id,
                    'caller': {
                        'id': call.caller.id,
                        'name': call.caller.get_full_name() or call.caller.email,
                        'email': call.caller.email,
                    },
                    'channel_name': call.channel_name,
                    'call_type': call.call_type,
                    'status': call.status,
                    'initiated_at': call.initiated_at,
                    'accepted_at': call.accepted_at,
                    'ended_at': call.ended_at,
                    'duration_minutes': call.duration_minutes,
                    'credits_deducted': float(call.credits_deducted) if call.credits_deducted else 0,
                    'ended_by': call.ended_by,
                }
                for call in calls_page
            ]
        }, status=status.HTTP_200_OK)
