# Generated by Django 5.0.6 on 2025-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeofwork',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
