# Generated by Django 5.0.6 on 2025-10-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polauser',
            name='user_type',
        ),
    ]
