# Generated by Django 5.2.7 on 2026-08-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(blank=True, default='', help_text='Plain OTP code (also stored hashed in otp_hash)', max_length=6),
        ),
    ]
