# Generated by Django 5.2.7 on 2026-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_device_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(help_text='Unique device identifier per user', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_id')},
        ),
    ]
