# Generated by Django 5.0.6 on 2025-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_placeofwork_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrole',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='legalspecialization',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
