# Generated by Django 5.0.6 on 2025-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_academicrole_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrole',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='legalspecialization',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
