# Generated by Django 5.0.6 on 2025-10-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_rolepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'role permission', 'verbose_name_plural': 'role permissions'},
        ),
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='authentication.RolePermission', to='auth.permission', verbose_name='permissions'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authentication.userrole'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest'), ('host', 'Host')], max_length=255, unique=True),
        ),
    ]
