# Generated by Django 5.0.6 on 2025-10-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_academicrole_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('roll_number_cert', 'Roll Number Certificate'), ('practice_license', 'Practice License'), ('work_certificate', 'Certificate of Work'), ('professional_cert', 'Professional Certificate'), ('employment_letter', 'Employment Letter'), ('organization_cert', 'Organization Certificate'), ('business_license', 'Business License'), ('registration_cert', 'Registration Certificate'), ('firm_documents', 'Other Firm Documents'), ('id_document', 'ID Document'), ('academic', 'Academic Certificate'), ('other', 'Other Document')], max_length=20),
        ),
    ]
