# Generated by Django 5.2.7 on 2026-08-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20260803'),
    ]

    operations = [
        migrations.AddField(
            model_name='polauser',
            name='associated_law_firm_name',
            field=models.CharField(blank=True, help_text='Name of the law firm the professional is associated with (if not registered on the platform).', max_length=255, null=True, verbose_name='Associated Law Firm Name'),
        ),
    ]
