# Generated by Django 5.2.7 on 2026-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_associated_law_firm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polauser',
            name='associated_law_firm_name',
        ),
    ]
