# Generated by Django 5.0.6 on 2025-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrole',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('roll_number_cert', 'Roll Number Certificate'), ('practice_license', 'Practice License'), ('work_certificate', 'Certificate of Work'), ('professional_cert', 'Professional Certificate'), ('employment_letter', 'Employment Letter'), ('organization_cert', 'Organization Certificate'), ('business_license', 'Business License'), ('registration_cert', 'Registration Certificate'), ('firm_documents', 'Other Firm Documents'), ('id_document', 'ID Document'), ('academic', 'Academic Certificate'), ('other', 'Other Document'), ('registration', 'Registration Certificate'), ('practice', 'Practice License')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legalspecialization',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='placeofwork',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
