# Generated by Django 5.0.6 on 2025-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_rolepermission_options_userrole_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lawyer', 'Lawyer/Advocate'), ('paralegal', 'Paralegal'), ('law_student', 'Law Student'), ('law_firm', 'Law Firm'), ('citizen', 'Citizen')], max_length=255, unique=True),
        ),
    ]
