# Generated by Django 5.0.6 on 2025-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userrole_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lawyer', 'Lawyer'), ('advocate', 'Advocate'), ('paralegal', 'Paralegal'), ('law_student', 'Law Student'), ('law_firm', 'Law Firm'), ('citizen', 'Citizen')], max_length=255, unique=True),
        ),
    ]
