# Generated by Django 5.2.7 on 2025-10-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_update_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polauser',
            name='regional_champter',
        ),
        migrations.CreateModel(
            name='RegionalChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the TLS regional chapter (e.g., 'Dar es Salaam Chapter', 'Arusha Chapter')", max_length=100, unique=True, verbose_name='Chapter Name')),
                ('code', models.CharField(blank=True, help_text="Short code for the chapter (e.g., 'DSM', 'ARU', 'MWZ')", max_length=20, null=True, unique=True, verbose_name='Chapter Code')),
                ('description', models.TextField(blank=True, help_text='Additional information about this chapter', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chapter is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='Geographic region where this chapter is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='authentication.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'regional chapter',
                'verbose_name_plural': 'regional chapters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='polauser',
            name='regional_chapter',
            field=models.ForeignKey(blank=True, help_text='TLS regional chapter where the advocate is registered (e.g., Dar es Salaam Chapter, Arusha Chapter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter_professionals', to='authentication.regionalchapter', verbose_name='Regional Chapter'),
        ),
    ]
