# Generated by Django 5.2.7 on 2026-09-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_accountdeletionrequest_userreport_blockeduser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('roll_number_cert', 'Roll Number Certificate'), ('practice_license', 'Practice License'), ('work_certificate', 'Certificate of Work'), ('professional_cert', 'Professional Certificate'), ('employment_letter', 'Employment Letter'), ('organization_cert', 'Organization Certificate'), ('business_license', 'Business License'), ('registration_cert', 'Registration Certificate'), ('firm_documents', 'Other Firm Documents'), ('id_document', 'ID Document'), ('academic', 'Academic Certificate'), ('other', 'Other Document'), ('registration', 'Registration Certificate'), ('practice', 'Practice License')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requirements', to='authentication.userrole')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('role', 'document_type')},
            },
        ),
    ]
