# Generated by Django 5.2.7 on 2025-10-22 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_regional_chapter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_reply_notifications', models.BooleanField(default=True, help_text='Notify when someone replies to your comment')),
                ('enable_like_notifications', models.BooleanField(default=True, help_text='Notify when someone likes your content')),
                ('enable_comment_notifications', models.BooleanField(default=True, help_text='Notify when someone comments on your content')),
                ('enable_message_notifications', models.BooleanField(default=True, help_text='Notify when you receive a private message')),
                ('enable_document_download_notifications', models.BooleanField(default=True, help_text='Notify when someone downloads your document')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable Do Not Disturb mode during specified hours')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours (e.g., 08:00)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='FCM device registration token', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='Type of device (iOS, Android, Web)', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='authenticat_user_id_bf39b9_idx'), models.Index(fields=['token'], name='authenticat_token_3f6a42_idx')],
            },
        ),
    ]
