# Generated by Django 5.2.7 on 2026-09-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_verificationrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='verificationrequirement',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='verificationrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='authentication.documenttype'),
        ),
        migrations.AddField(
            model_name='verificationrequirement',
            name='document_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_requirements', to='authentication.documenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationrequirement',
            unique_together={('role', 'document_type_ref')},
        ),
    ]
