# Generated by Django 5.2.7 on 2025-10-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_firebase_notification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='polauser',
            name='year_of_admission_to_bar',
            field=models.IntegerField(blank=True, help_text='Year when the advocate was admitted to the bar (for advocates)', null=True, verbose_name='Year of Admission to Bar'),
        ),
        migrations.AlterField(
            model_name='polauser',
            name='place_of_work',
            field=models.ForeignKey(blank=True, help_text='Current workplace/office where the professional is working (Law Firm, Legal Aid, Government Agency, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='authentication.placeofwork', verbose_name='Place of Work/Office'),
        ),
    ]
