# Generated by Django 5.2.7 on 2025-10-25 08:14

from django.db import migrations


def add_lecturer_role(apps, schema_editor):
    """Add lecturer role to the database"""
    UserRole = apps.get_model('authentication', 'UserRole')
    
    # Check if lecturer role already exists
    if not UserRole.objects.filter(role_name='lecturer').exists():
        UserRole.objects.create(
            role_name='lecturer',
            description='University lecturer teaching law'
        )
        print("✅ Lecturer role created successfully")
    else:
        print("ℹ️ Lecturer role already exists")


def remove_lecturer_role(apps, schema_editor):
    """Remove lecturer role (for reverting migration)"""
    UserRole = apps.get_model('authentication', 'UserRole')
    UserRole.objects.filter(role_name='lecturer').delete()
    print("🗑️ Lecturer role removed")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_polauser_year_of_admission_to_bar_and_more'),
    ]

    operations = [
        migrations.RunPython(add_lecturer_role, remove_lecturer_role),
    ]
