# Generated by Django 4.2.24 on 2025-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_add_lecturer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('lawyer', 'Lawyer'), ('advocate', 'Advocate'), ('paralegal', 'Paralegal'), ('law_student', 'Law Student'), ('lecturer', 'Lecturer'), ('law_firm', 'Law Firm'), ('citizen', 'Citizen')], max_length=255, unique=True),
        ),
    ]
