# Generated by Django 5.2.7 on 2025-12-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_userdevice_loginhistory_usersession_securityalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('emulator', 'Emulator'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
