# Generated by Django 5.2.7 on 2025-12-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_userdevice_latitude_userdevice_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
