# Generated by Django 5.2.7 on 2025-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_userdevice_latitude_alter_userdevice_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='is_current_device',
            field=models.BooleanField(default=False, help_text='Currently active device for this user'),
        ),
    ]
