# Generated by Django 5.2.7 on 2026-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_userdevice_is_current_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description of the role', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Swahili description of the role', null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('advocate', 'Advocate'), ('lawyer', 'Lawyer'), ('paralegal', 'Paralegal'), ('law_firm', 'Law Firm'), ('law_student', 'Law Student'), ('lecturer', 'Lecturer')], max_length=255, unique=True),
        ),
    ]
