# Generated by Django 5.2.7 on 2026-01-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_add_bilingual_role_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='polauser',
            name='occupation',
            field=models.CharField(blank=True, help_text="User's occupation or profession (Kazi/Shughuli)", max_length=255, null=True, verbose_name='Occupation'),
        ),
    ]
