# Generated by Django 5.2.7 on 2026-01-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_add_occupation_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_tagging', models.CharField(choices=[('everyone', 'Everyone can tag me'), ('following', 'Only people I follow can tag me'), ('none', 'No one can tag me')], default='everyone', help_text='Who can tag you in comments and posts', max_length=20)),
                ('notify_on_tag', models.BooleanField(default=True, help_text='Receive notification when tagged')),
                ('show_email', models.BooleanField(default=False, help_text='Show email on public profile')),
                ('show_phone', models.BooleanField(default=False, help_text='Show phone number on public profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Privacy Settings',
                'verbose_name_plural': 'User Privacy Settings',
            },
        ),
    ]
