# Generated by Django 5.2.7 on 2026-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_userprivacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='polauser',
            name='username',
            field=models.CharField(blank=True, help_text='Username for @mentions and tagging. Auto-generated from email if not provided.', max_length=150, null=True, unique=True),
        ),
    ]
