# FCM endpoint
import json
import requests


class FCM:
    def __init__(self, project_id, access_token):
        self.project_id = project_id
        self.access_token = access_token
        self.url = f'https://fcm.googleapis.com/v1/projects/{project_id}/messages:send'
        self.headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json; UTF-8',
        }

    def send_notification(self, device_registration_token, title, body, data):
        """
        Send a general push notification with high priority
        """
        payload = {
            "message": {
                "token": device_registration_token,
                "notification": {
                    "title": title,
                    "body": body
                },
                "data": data,
                "android": {
                    "priority": "high",
                    "notification": {
                        "channel_id": "general_notifications",
                        "sound": "default",
                        "default_vibrate_timings": True
                    }
                },
                "apns": {
                    "headers": {
                        "apns-priority": "10"
                    },
                    "payload": {
                        "aps": {
                            "sound": "default",
                            "content-available": 1,
                            "badge": 1
                        }
                    }
                }
            }
        }
        response = requests.post(self.url, headers=self.headers, data=json.dumps(payload))
        return response.status_code, response.json()
    
    def send_call_notification(self, device_registration_token, call_data):
        """
        Send high-priority incoming call notification
        
        Args:
            device_registration_token: FCM device token
            call_data: dict with keys:
                - call_id: str
                - channel_name: str (generated by frontend app)
                - caller_id: str
                - caller_name: str
                - caller_photo: str (optional)
                - call_type: str (voice or video)
        
        Returns:
            tuple: (status_code, response_json)
        """
        # Ensure all data values are strings for FCM
        data_payload = {
            'type': 'incoming_call',
            'call_id': str(call_data.get('call_id', '')),
            'channel_name': str(call_data.get('channel_name', '')),
            'caller_id': str(call_data.get('caller_id', '')),
            'caller_name': str(call_data.get('caller_name', '')),
            'caller_photo': str(call_data.get('caller_photo', '')),
            'call_type': str(call_data.get('call_type', 'voice')),
            'timestamp': str(call_data.get('timestamp', ''))
        }
        
        payload = {
            "message": {
                "token": device_registration_token,
                "notification": {
                    "title": "Incoming Call",
                    "body": f"{call_data.get('caller_name', 'Someone')} is calling you"
                },
                "data": data_payload,
                "android": {
                    "priority": "high",
                    "notification": {
                        "channel_id": "incoming_calls",
                        "sound": "ringtone.mp3",
                        "default_vibrate_timings": True
                    }
                },
                "apns": {
                    "headers": {
                        "apns-priority": "10"
                    },
                    "payload": {
                        "aps": {
                            "sound": "ringtone.caf",
                            "content-available": 1,
                            "badge": 1
                        }
                    }
                }
            }
        }
        
        response = requests.post(self.url, headers=self.headers, data=json.dumps(payload))
        return response.status_code, response.json()
    
    def send_call_status_notification(self, device_registration_token, status_data):
        """
        Send call status notification (accepted, rejected, ended, missed)
        
        Args:
            device_registration_token: FCM device token
            status_data: dict with keys:
                - type: str (call_accepted, call_rejected, call_ended, missed_call)
                - call_id: str
                - message: str
        """
        # Ensure all data values are strings
        data_payload = {
            'type': str(status_data.get('type', '')),
            'call_id': str(status_data.get('call_id', '')),
            'message': str(status_data.get('message', ''))
        }
        
        payload = {
            "message": {
                "token": device_registration_token,
                "data": data_payload,
                "android": {
                    "priority": "high"
                },
                "apns": {
                    "headers": {
                        "apns-priority": "10"
                    }
                }
            }
        }
        
        response = requests.post(self.url, headers=self.headers, data=json.dumps(payload))
        return response.status_code, response.json()    
