# Generated by Django 5.2.7 on 2025-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', help_text='Price currency', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='TZS', help_text='Transaction currency', max_length=3),
        ),
    ]
