# Generated by Django 5.2.7 on 2025-10-15 17:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_duplicate_professional_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callcreditbundle',
            options={'ordering': ['price'], 'verbose_name': 'Call Credit Bundle (Consultation Voucher)', 'verbose_name_plural': 'Call Credit Bundles (Consultation Vouchers)'},
        ),
        migrations.AlterField(
            model_name='callcreditbundle',
            name='validity_days',
            field=models.IntegerField(help_text='Days until expiry after purchase (carry forward period)'),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='consultant_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Consultant/Uploader share percentage (50% for mobile, 40% for physical, varies for materials)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Platform commission percentage (50% for mobile, 60% for physical, varies for materials)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='service_type',
            field=models.CharField(choices=[('MOBILE_ADVOCATE', 'Mobile Consultation - Advocate (In-App Call)'), ('MOBILE_LAWYER', 'Mobile Consultation - Lawyer (In-App Call)'), ('MOBILE_PARALEGAL', 'Mobile Consultation - Paralegal (In-App Call)'), ('PHYSICAL_ADVOCATE', 'Physical Consultation - Advocate'), ('PHYSICAL_LAWYER', 'Physical Consultation - Lawyer'), ('PHYSICAL_PARALEGAL', 'Physical Consultation - Paralegal'), ('DOCUMENT_STANDARD', 'Standard Document Generation'), ('DOCUMENT_ADVANCED', 'Advanced Document Generation'), ('MATERIAL_STUDENT', 'Study Material - Student Upload'), ('MATERIAL_LECTURER', 'Study Material - Lecturer Upload'), ('MATERIAL_ADMIN', 'Study Material - Admin Upload')], max_length=50, unique=True),
        ),
    ]
