# Generated by Django 5.2.7 on 2025-10-15 18:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_update_pricing_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(help_text='Phone number for mobile money (255XXXXXXXXX)', max_length=15)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('disbursement_type', models.CharField(choices=[('consultant', 'Consultant Earnings'), ('uploader', 'Uploader Earnings'), ('refund', 'Refund'), ('other', 'Other')], default='consultant', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_method', models.CharField(choices=[('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('halopesa', 'Halopesa'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('azampay_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_reference', models.CharField(help_text='Internal reference ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if status is failed')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultant_earnings', models.ManyToManyField(blank=True, related_name='disbursements', to='subscriptions.consultantearnings')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_disbursements', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to=settings.AUTH_USER_MODEL)),
                ('uploader_earnings', models.ManyToManyField(blank=True, related_name='disbursements', to='subscriptions.uploaderearnings')),
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['-initiated_at'], name='subscriptio_initiat_fc6bee_idx'), models.Index(fields=['status'], name='subscriptio_status_ee3e6c_idx'), models.Index(fields=['recipient', '-initiated_at'], name='subscriptio_recipie_f207e8_idx')],
            },
        ),
    ]
