# Generated by Django 5.2.7 on 2025-10-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='account_verified',
            field=models.BooleanField(default=False, help_text='Whether account was verified via name inquiry'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code/SWIFT code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name', max_length=100, null=True),
        ),
    ]
