# Generated by Django 5.0.6 on 2025-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_add_bank_fields_to_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcreditbundle',
            name='description',
            field=models.TextField(blank=True, help_text='English description of the bundle'),
        ),
        migrations.AddField(
            model_name='callcreditbundle',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Swahili description of the bundle'),
        ),
    ]
