# Generated by Django 5.0.6 on 2025-10-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_callcreditbundle_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcreditbundle',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Swahili name', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcreditbundle',
            name='name',
            field=models.CharField(help_text='English name', max_length=100),
        ),
    ]
