# Generated by Django 5.2.7 on 2025-10-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_hub_alter_legaledsubtopic_options_and_more'),
        ('subscriptions', '0009_callcreditbundle_name_sw_alter_callcreditbundle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='content_type',
            field=models.CharField(choices=[('file', 'File (PDF, DOC, etc)'), ('rich_text', 'Rich Text/HTML')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='is_downloadable',
            field=models.BooleanField(default=True, help_text='Allow users to download this material'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', help_text='Content language', max_length=2),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='rich_text_content',
            field=models.TextField(blank=True, help_text='Rich text/HTML content'),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='subtopic',
            field=models.ForeignKey(blank=True, help_text='Link to hub subtopic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hubs.legaledsubtopic'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='category',
            field=models.CharField(choices=[('notes', 'Study Notes'), ('past_papers', 'Past Exam Papers'), ('assignments', 'Assignments'), ('tutorials', 'Tutorials'), ('hub_content', 'Hub Content'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='File content (PDF, DOC, etc)', null=True, upload_to='learning_materials/'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
    ]
