# Generated by Django 5.2.7 on 2025-10-21 08:55
# Modified: LearningMaterial and LearningMaterialPurchase moved to documents app
# These operations are now state-only since documents app manages the tables

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        # No-op migration - models already moved to documents app
    ]
