# Generated by Django 5.2.7 on 2026-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_uploaderearnings_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='consultant_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm'), ('advocate', 'Advocate'), ('lawyer', 'Lawyer'), ('paralegal', 'Paralegal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultantregistrationrequest',
            name='consultant_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm'), ('advocate', 'Advocate'), ('lawyer', 'Lawyer'), ('paralegal', 'Paralegal')], max_length=20),
        ),
    ]
