# Generated by Django 5.2.7 on 2025-11-25 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_uploaderearnings_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text="Client's written review")),
                ('professionalism_rating', models.IntegerField(blank=True, help_text='Professionalism rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(blank=True, help_text='Communication clarity rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('expertise_rating', models.IntegerField(blank=True, help_text='Legal expertise rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('consultant_response', models.TextField(blank=True, help_text="Consultant's response to review")),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide review')),
                ('flagged', models.BooleanField(default=False, help_text='Flagged for moderation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='subscriptions.consultationbooking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultant Review',
                'verbose_name_plural': 'Consultant Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'client')},
            },
        ),
    ]
