# Generated by Django 5.2.7 on 2026-03-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_consultantprofile_consultant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantregistrationrequest',
            name='id_document',
            field=models.FileField(blank=True, help_text='National ID or Passport for identity verification', null=True, upload_to='consultant_ids/'),
        ),
    ]
