# Generated by Django 4.2.24 on 2025-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_consultantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsession',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='subscriptions.consultationbooking'),
        ),
    ]
