# Generated by Django 5.2.7 on 2025-12-14 13:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_make_callsession_booking_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callsession',
            options={'ordering': ['-initiated_at'], 'verbose_name': 'Call Session', 'verbose_name_plural': 'Call Sessions'},
        ),
        migrations.AddField(
            model_name='callsession',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When consultant accepted', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='call_type',
            field=models.CharField(choices=[('voice', 'Voice Call'), ('video', 'Video Call')], default='voice', max_length=20),
        ),
        migrations.AddField(
            model_name='callsession',
            name='caller',
            field=models.ForeignKey(blank=True, help_text='User who initiated the call', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='channel_name',
            field=models.CharField(blank=True, help_text='Agora channel name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='consultant',
            field=models.ForeignKey(blank=True, help_text='Consultant receiving the call', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsession',
            name='credits_deducted',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='callsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When call ended', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='ended_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('consultant', 'Consultant'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='initiated_at',
            field=models.DateTimeField(blank=True, help_text='When call was initiated', null=True),
        ),
        migrations.AddField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='ringing', max_length=50),
        ),
        migrations.AddField(
            model_name='callsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='call_quality_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['caller', 'status'], name='subscriptio_caller__d87821_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['consultant', 'status'], name='subscriptio_consult_012808_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['channel_name'], name='subscriptio_channel_f59c61_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['status', 'initiated_at'], name='subscriptio_status_06fa91_idx'),
        ),
    ]
