# Generated by Django 5.2.7 on 2026-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='payment_method',
            field=models.CharField(choices=[('Airtel', 'Airtel Money'), ('Tigo', 'Tigo Pesa'), ('Halopesa', 'Halopesa'), ('Azampesa', 'Azam Pesa'), ('Mpesa', 'M-Pesa'), ('CRDB', 'CRDB Bank'), ('NMB', 'NMB Bank'), ('bank', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('Airtel', 'Airtel Money'), ('Tigo', 'Tigo Pesa'), ('Halopesa', 'Halopesa'), ('Azampesa', 'Azam Pesa'), ('Mpesa', 'M-Pesa'), ('CRDB', 'CRDB Bank'), ('NMB', 'NMB Bank'), ('bank', 'Bank Transfer')], max_length=50),
        ),
    ]
