# Generated by Django 5.2.7 on 2025-12-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_make_material_optional_in_questions'),
        ('subscriptions', '0014_alter_callsession_options_callsession_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='fulfillment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_fulfilled',
            field=models.BooleanField(default=False, help_text='Has the purchase been delivered/activated?'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='item_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store item details (plan name, bundle info, document title, etc.)'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='related_call_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='subscriptions.usercallcredit'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='related_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='subscriptions.generateddocument'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='related_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='documents.learningmaterial'),
        ),
    ]
