# Generated by Django 5.2.7 on 2025-12-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_paymenttransaction_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callcreditbundle',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TZS', help_text='Price currency', max_length=3),
        ),
    ]
