# Generated by Django 5.2.7 on 2026-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_add_currency_to_call_credit_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='consultant_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='consultantregistrationrequest',
            name='consultant_type',
            field=models.CharField(choices=[('law_firm', 'Law Firm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='service_type',
            field=models.CharField(choices=[('MOBILE_LAW_FIRM', 'Mobile Consultation - Law Firm (In-App Call)'), ('PHYSICAL_LAW_FIRM', 'Physical Consultation - Law Firm'), ('MOBILE_ADVOCATE', 'Mobile Consultation - Advocate (DEPRECATED)'), ('MOBILE_LAWYER', 'Mobile Consultation - Lawyer (DEPRECATED)'), ('MOBILE_PARALEGAL', 'Mobile Consultation - Paralegal (DEPRECATED)'), ('PHYSICAL_ADVOCATE', 'Physical Consultation - Advocate (DEPRECATED)'), ('PHYSICAL_LAWYER', 'Physical Consultation - Lawyer (DEPRECATED)'), ('PHYSICAL_PARALEGAL', 'Physical Consultation - Paralegal (DEPRECATED)'), ('DOCUMENT_STANDARD', 'Standard Document Generation'), ('DOCUMENT_ADVANCED', 'Advanced Document Generation'), ('MATERIAL_STUDENT', 'Study Material - Student Upload'), ('MATERIAL_LECTURER', 'Study Material - Lecturer Upload'), ('MATERIAL_ADMIN', 'Study Material - Admin Upload')], max_length=50, unique=True),
        ),
    ]
