# Generated by Django 5.2.7 on 2026-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_law_firm_only_consultants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationbooking',
            name='booking_type',
            field=models.CharField(choices=[('physical', 'Physical Consultation')], max_length=20),
        ),
    ]
