# Generated by Django 5.2.7 on 2026-02-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEdTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Topic name in English', max_length=255)),
                ('name_sw', models.CharField(blank=True, help_text='Topic name in Swahili', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Topic description in English', null=True)),
                ('description_sw', models.TextField(blank=True, help_text='Topic description in Swahili', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon for this topic', max_length=100)),
                ('display_order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Education Topic',
                'verbose_name_plural': 'Legal Education Topics',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Forum'), ('legal_ed', 'Legal Education')], db_index=True, max_length=20)),
                ('comment_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_comments', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(help_text='The post/document being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.learningmaterial')),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents attached to this comment', related_name='attached_in_comments', to='documents.learningmaterial')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hubs.hubcomment')),
            ],
            options={
                'verbose_name': 'Hub Comment',
                'verbose_name_plural': 'Hub Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Character position in comment where mention starts')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the mentioned user has seen the mention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentioned_by', models.ForeignKey(help_text='The user who created the mention', on_delete=django.db.models.deletion.CASCADE, related_name='mentions_created', to=settings.AUTH_USER_MODEL)),
                ('mentioned_user', models.ForeignKey(help_text='The user who was mentioned/tagged', on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(help_text='The comment where the user was mentioned', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='hubs.hubcomment')),
            ],
            options={
                'verbose_name': 'Comment Mention',
                'verbose_name_plural': 'Comment Mentions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hubs.hubcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='HubMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Forum'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hub_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hub_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalEdSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subtopic name in English', max_length=255)),
                ('name_sw', models.CharField(blank=True, help_text='Subtopic name in Swahili', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Subtopic description in English', null=True)),
                ('description_sw', models.TextField(blank=True, help_text='Subtopic description in Swahili', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order within topic')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='hubs.legaledtopic')),
            ],
            options={
                'verbose_name': 'SubTopic',
                'verbose_name_plural': 'SubTopics',
                'ordering': ['topic', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentHubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_comments_deprecated', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_comments_deprecated', to='documents.learningmaterial')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hubs.studenthubcomment')),
            ],
            options={
                'verbose_name': 'Document Comment (Deprecated)',
                'verbose_name_plural': 'Document Comments (Deprecated)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHubCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hubs.studenthubcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='StudentHubDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times re-downloaded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_downloaded_at', models.DateTimeField(auto_now=True)),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_downloads_deprecated', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_downloads_deprecated', to='documents.learningmaterial')),
            ],
            options={
                'verbose_name': 'Student Hub Download (Deprecated)',
                'verbose_name_plural': 'Student Hub Downloads (Deprecated)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='documents.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Bookmark',
                'verbose_name_plural': 'Content Bookmarks',
                'indexes': [models.Index(fields=['user', '-created_at'], name='hubs_conten_user_id_1eea70_idx')],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='documents.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Like',
                'verbose_name_plural': 'Content Likes',
                'indexes': [models.Index(fields=['user', '-created_at'], name='hubs_conten_user_id_e62bc0_idx'), models.Index(fields=['content', '-created_at'], name='hubs_conten_content_1e52d7_idx')],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.AddIndex(
            model_name='hubcomment',
            index=models.Index(fields=['hub_type', 'content', 'created_at'], name='hubs_hubcom_hub_typ_6a9afc_idx'),
        ),
        migrations.AddIndex(
            model_name='hubcomment',
            index=models.Index(fields=['author', '-created_at'], name='hubs_hubcom_author__659d57_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='hubs_commen_mention_e7fdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['comment', 'mentioned_user'], name='hubs_commen_comment_cedc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmention',
            index=models.Index(fields=['mentioned_user', 'is_read'], name='hubs_commen_mention_de1875_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentmention',
            unique_together={('comment', 'mentioned_user', 'position')},
        ),
        migrations.AddIndex(
            model_name='hubcommentlike',
            index=models.Index(fields=['user', '-created_at'], name='hubs_hubcom_user_id_9ab948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hubcommentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='hubmessage',
            index=models.Index(fields=['hub_type', 'recipient', '-created_at'], name='hubs_hubmes_hub_typ_823c63_idx'),
        ),
        migrations.AddIndex(
            model_name='hubmessage',
            index=models.Index(fields=['hub_type', 'sender', '-created_at'], name='hubs_hubmes_hub_typ_5f4ce6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legaledsubtopic',
            unique_together={('topic', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='studenthubcommentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='studenthubdownload',
            unique_together={('material', 'downloader')},
        ),
    ]
