# Generated by Django 5.2.7 on 2025-10-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hub name in English', max_length=255)),
                ('name_sw', models.CharField(blank=True, help_text='Hub name in Swahili', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('hub_type', models.CharField(choices=[('legal_education', 'Legal Education Hub'), ('student_hub', 'Student Hub'), ('professional_development', 'Professional Development'), ('legal_updates', 'Legal Updates & News'), ('other', 'Other')], default='legal_education', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Hub description in English')),
                ('description_sw', models.TextField(blank=True, help_text='Hub description in Swahili')),
                ('icon', models.CharField(blank=True, help_text='Icon name or path', max_length=100)),
                ('color', models.CharField(default='#1976D2', help_text='Hex color code for UI', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which hubs are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub',
                'verbose_name_plural': 'Hubs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='legaledsubtopic',
            options={'ordering': ['topic', 'display_order', 'name'], 'verbose_name': 'SubTopic', 'verbose_name_plural': 'SubTopics'},
        ),
        migrations.AlterModelOptions(
            name='legaledtopic',
            options={'ordering': ['hub', 'display_order', 'name'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='legaledsubtopic',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order within topic'),
        ),
        migrations.AddField(
            model_name='legaledsubtopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legaledsubtopic',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='legaledtopic',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Display order within hub'),
        ),
        migrations.AddField(
            model_name='legaledtopic',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon for this topic', max_length=100),
        ),
        migrations.AddField(
            model_name='legaledtopic',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='legaledtopic',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='legaledsubtopic',
            name='description',
            field=models.TextField(blank=True, help_text='Subtopic description in English', null=True),
        ),
        migrations.AlterField(
            model_name='legaledsubtopic',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Subtopic description in Swahili', null=True),
        ),
        migrations.AlterField(
            model_name='legaledsubtopic',
            name='name',
            field=models.CharField(help_text='Subtopic name in English', max_length=255),
        ),
        migrations.AlterField(
            model_name='legaledsubtopic',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Subtopic name in Swahili', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legaledtopic',
            name='description',
            field=models.TextField(blank=True, help_text='Topic description in English', null=True),
        ),
        migrations.AlterField(
            model_name='legaledtopic',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Topic description in Swahili', null=True),
        ),
        migrations.AlterField(
            model_name='legaledtopic',
            name='name',
            field=models.CharField(help_text='Topic name in English', max_length=255),
        ),
        migrations.AlterField(
            model_name='legaledtopic',
            name='name_sw',
            field=models.CharField(blank=True, help_text='Topic name in Swahili', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='legaledsubtopic',
            unique_together={('topic', 'slug')},
        ),
        migrations.AddField(
            model_name='legaledtopic',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='Parent hub', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='hubs.hub'),
        ),
        migrations.AlterUniqueTogether(
            name='legaledtopic',
            unique_together={('hub', 'slug')},
        ),
    ]
