# Generated by Django 5.2.7 on 2025-10-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('hubs', '0003_alter_legaledtopic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthubcomment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_comments', to='documents.learningmaterial'),
        ),
        migrations.AlterField(
            model_name='studenthubdownload',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_downloads', to='documents.learningmaterial'),
        ),
    ]
