# Generated by Django 5.0.6 on 2025-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('hubs', '0004_alter_studenthubcomment_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocatepost',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Attached learning materials/documents', related_name='advocate_posts', to='documents.learningmaterial'),
        ),
    ]
