# Generated by Django 5.0.6 on 2025-10-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0005_alter_advocatepost_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocatecomment',
            name='attached_documents',
        ),
        migrations.DeleteModel(
            name='AdvocateDocument',
        ),
    ]
