# Generated by Django 5.0.6 on 2025-10-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0006_remove_advocatecomment_attached_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocatecomment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='advocatepost',
            name='bookmarks_count',
        ),
        migrations.RemoveField(
            model_name='advocatepost',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='advocatepost',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='studenthubcomment',
            name='likes_count',
        ),
    ]
