# Generated by Django 5.0.6 on 2025-10-22 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_extend_learning_material_unified_content'),
        ('hubs', '0009_unified_content_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocatecommentlike',
            name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='advocatecommentlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='advocatecommentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advocatemessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='advocatemessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='advocatepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='advocatepost',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='advocatepostlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='advocatepostbookmark',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='advocatepostbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='advocatepostbookmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='advocatepostlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='advocatepostlike',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='studenthubcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Document Comment (Deprecated)', 'verbose_name_plural': 'Document Comments (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='studenthubdownload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Hub Download (Deprecated)', 'verbose_name_plural': 'Student Hub Downloads (Deprecated)'},
        ),
        migrations.AlterField(
            model_name='studenthubcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_comments_deprecated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenthubcomment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_comments_deprecated', to='documents.learningmaterial'),
        ),
        migrations.AlterField(
            model_name='studenthubdownload',
            name='downloader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_downloads_deprecated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studenthubdownload',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_hub_downloads_deprecated', to='documents.learningmaterial'),
        ),
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='documents.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Bookmark',
                'verbose_name_plural': 'Content Bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='documents.learningmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Like',
                'verbose_name_plural': 'Content Likes',
            },
        ),
        migrations.CreateModel(
            name='HubComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Forum'), ('legal_ed', 'Legal Education')], db_index=True, max_length=20)),
                ('comment_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_comments', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(help_text='The post/document being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.learningmaterial')),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents attached to this comment', related_name='attached_in_comments', to='documents.learningmaterial')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hubs.hubcomment')),
            ],
            options={
                'verbose_name': 'Hub Comment',
                'verbose_name_plural': 'Hub Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HubCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hubs.hubcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Like',
                'verbose_name_plural': 'Comment Likes',
            },
        ),
        migrations.CreateModel(
            name='HubMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_type', models.CharField(choices=[('advocates', 'Advocates Hub'), ('students', 'Students Hub'), ('forum', 'Forum'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hub_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_hub_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdvocateComment',
        ),
        migrations.DeleteModel(
            name='AdvocateCommentLike',
        ),
        migrations.DeleteModel(
            name='AdvocateMessage',
        ),
        migrations.DeleteModel(
            name='AdvocatePost',
        ),
        migrations.DeleteModel(
            name='AdvocatePostBookmark',
        ),
        migrations.DeleteModel(
            name='AdvocatePostLike',
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['user', '-created_at'], name='hubs_conten_user_id_1eea70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentbookmark',
            unique_together={('user', 'content')},
        ),
        migrations.AddIndex(
            model_name='contentlike',
            index=models.Index(fields=['user', '-created_at'], name='hubs_conten_user_id_e62bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentlike',
            index=models.Index(fields=['content', '-created_at'], name='hubs_conten_content_1e52d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentlike',
            unique_together={('user', 'content')},
        ),
        migrations.AddIndex(
            model_name='hubcomment',
            index=models.Index(fields=['hub_type', 'content', 'created_at'], name='hubs_hubcom_hub_typ_6a9afc_idx'),
        ),
        migrations.AddIndex(
            model_name='hubcomment',
            index=models.Index(fields=['author', '-created_at'], name='hubs_hubcom_author__659d57_idx'),
        ),
        migrations.AddIndex(
            model_name='hubcommentlike',
            index=models.Index(fields=['user', '-created_at'], name='hubs_hubcom_user_id_9ab948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hubcommentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='hubmessage',
            index=models.Index(fields=['hub_type', 'recipient', '-created_at'], name='hubs_hubmes_hub_typ_823c63_idx'),
        ),
        migrations.AddIndex(
            model_name='hubmessage',
            index=models.Index(fields=['hub_type', 'sender', '-created_at'], name='hubs_hubmes_hub_typ_5f4ce6_idx'),
        ),
    ]
