# Generated by Django 5.0.6 on 2025-10-22 15:26
# Modified to handle tables that were already created by migrations 0008 and 0009

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        ('hubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No-op migration - models already renamed and properly configured
    ]
