# Generated by Django 5.2.7 on 2026-03-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0010_remove_advocatecommentlike_comment_and_more'),
        ('subscriptions', '0013_alter_consultantregistrationrequest_id_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthubcommentlike',
            options={'verbose_name': 'Comment Like'},
        ),
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('time_extended', 'Time Extended'), ('end_date_changed', 'End Date Changed'), ('period_reset', 'Period Reset'), ('bulk_time_extended', 'Bulk Time Extended'), ('status_changed', 'Status Changed'), ('plan_changed', 'Plan Changed'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=50)),
                ('old_start_date', models.DateTimeField(blank=True, help_text='Previous start date before change', null=True)),
                ('new_start_date', models.DateTimeField(blank=True, help_text='New start date after change', null=True)),
                ('old_end_date', models.DateTimeField(blank=True, help_text='Previous end date before change', null=True)),
                ('new_end_date', models.DateTimeField(blank=True, help_text='New end date after change', null=True)),
                ('old_status', models.CharField(blank=True, help_text='Previous status before change', max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, help_text='New status after change', max_length=20, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for the change', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of admin who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of admin who made the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'Subscription Log',
                'verbose_name_plural': 'Subscription Logs',
                'db_table': 'hubs_subscription_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'created_at'], name='hubs_subscr_subscri_933b21_idx'), models.Index(fields=['action', 'created_at'], name='hubs_subscr_action_154b68_idx'), models.Index(fields=['admin_user', 'created_at'], name='hubs_subscr_admin_u_d10f00_idx')],
            },
        ),
    ]
