# Generated by Django 5.2.7 on 2026-01-24 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0010_remove_advocatecommentlike_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Character position in comment where mention starts')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the mentioned user has seen the mention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(help_text='The comment where the user was mentioned', on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='hubs.hubcomment')),
                ('mentioned_by', models.ForeignKey(help_text='The user who created the mention', on_delete=django.db.models.deletion.CASCADE, related_name='mentions_created', to=settings.AUTH_USER_MODEL)),
                ('mentioned_user', models.ForeignKey(help_text='The user who was mentioned/tagged', on_delete=django.db.models.deletion.CASCADE, related_name='comment_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment Mention',
                'verbose_name_plural': 'Comment Mentions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentioned_user', '-created_at'], name='hubs_commen_mention_e7fdb3_idx'), models.Index(fields=['comment', 'mentioned_user'], name='hubs_commen_comment_cedc7a_idx'), models.Index(fields=['mentioned_user', 'is_read'], name='hubs_commen_mention_de1875_idx')],
                'unique_together': {('comment', 'mentioned_user', 'position')},
            },
        ),
    ]
