# Generated by Django 5.2.7 on 2026-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0011_alter_studenthubcommentlike_options_subscriptionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaledsubtopic',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True),
        ),
    ]
