# Generated by Django 5.2.7 on 2026-06-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0012_alter_legaledsubtopic_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legaledsubtopic',
            unique_together={('topic', 'name')},
        ),
    ]
