# Generated by Django 5.2.7 on 2026-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0013_alter_legaledsubtopic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaledsubtopic',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', help_text='Primary language of this subtopic', max_length=2),
        ),
    ]
