# Generated by Django 5.2.7 on 2026-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0014_legaledsubtopic_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaledtopic',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', help_text='Primary language of this topic (all subtopics will inherit this language)', max_length=2),
        ),
    ]
